/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#include "./gen-cpp2/ExampleService.h"
#include "./gen-cpp2/ExampleService.tcc"

namespace tamvm { namespace cpp2 {
}} // tamvm::cpp2
namespace apache { namespace thrift {

}} // apache::thrift
