/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "./gen-cpp2/example_types.h"
#include "./gen-cpp2/example_types.tcc"

#include <algorithm>
#include <folly/Indestructible.h>

#include "./gen-cpp2/example_data.h"


namespace apache {
namespace thrift {
namespace detail {


} // namespace detail
} // namespace thrift
} // namespace apache

