/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#include "./gen-cpp2/example_constants.h"

#include <folly/Indestructible.h>

namespace tamvm { namespace cpp2 {

}} // tamvm::cpp2
